---
- name: Listen for alert notifications from Kentik
  hosts: localhost
  ## Listening on port 5000.
  sources:
    - kentik.ansible_eda.kentik_webhook:
        host: 0.0.0.0
        port: 5000
  rules:
      ## Checking for critical issues with HTTP tests
    - name: Web Application Down - Critical Error
      condition: event.payload.TestType == 'HTTP(S) or API' and event.payload.AlarmSeverity == 'critical'
      ## Restart the webservice
      action:
        run_job_template:
          name: EDADemo-action-kentik-restart-apache
          organization: "{{ job_templates_org_name | default('Foxhound') }}"
          job_args:
            extra_vars:
              reporting_host: "{{ event.payload.issue[0].Target }}"
