---
- name: Restart The Apache service
  hosts: "{{ reporting_host | basename }}"
  gather_facts: false
  become: true
  tasks:
    - name: Restart apache service
      ansible.builtin.service:
        name: httpd
        state: restarted
